let DATA = {
    users: [
        {
            id: 1,
            isActive: true,
            fname: "John",
            lname: "Doe",
            username: "johndoe",
            password: "12345678",
            gander: 'Male',
            budget: 0,
            email: "email 1",
            url: "https://thumbs.dreamstime.com/b/laptop-computer-user-icon-vector-isolated-white-person-work-online-pictogram-business-worker-analyst-student-coder-customer-316853739.jpg",
            age: 14
        },
        {
            id: 2,
            isActive: true,
            fname: "Jahn",
            lname: "Doe",
            username: "janedoe",
            password: "12345678",
            gander: 'Male',
            budget: 0,
            email: "email 2",
            url: "https://wac-cdn.atlassian.com/dam/jcr:ba03a215-2f45-40f5-8540-b2015223c918/Max-R_Headshot%20(1).jpg?cdnVersion=2081",
            age: 32
        },
        {
            id: 3,
            isActive: true,
            fname: "Alice",
            lname: "Johnson",
            username: "alicej",
            password: "password123",
            gander: 'Male',
            budget: 0,
            email: "email 3",
            url: "https://images.ctfassets.net/lh3zuq09vnm2/yBDals8aU8RWtb0xLnPkI/19b391bda8f43e16e64d40b55561e5cd/How_tracking_user_behavior_on_your_website_can_improve_customer_experience.png",
            age: 11
        },
        {
            id: 4,
            isActive: true,
            fname: "Bob",
            lname: "Smith",
            username: "bobsmith",
            password: "password123",
            gander: 'Male',
            budget: 0,
            email: "email 4",
            url: "https://img.freepik.com/premium-photo/cute-children-baby-boy-smiling-reading-book-white-background-generative-by-ai_39704-6017.jpg",
            age: 17
        },
        {
            id: 5,
            isActive: true,
            fname: "Carol",
            lname: "White",
            username: "carolw",
            password: "password123",
            gander: 'Male',
            budget: 0,
            email: "email 5",
            url: "https://play-lh.googleusercontent.com/tryRowcXJHdoAT0SIO-WBxEdudjvZmTicjuVHJuadKAJ76KgKiq22hMqDXB9sCq3pw=w240-h480-rw",
            age: 50
        },
        {
            id: 6,
            isActive: true,
            fname: "Dave",
            lname: "Brown",
            username: "daveb",
            password: "password123",
            gander: 'Male',
            budget: 0,
            email: "email 6",
            url: "https://miro.medium.com/v2/resize:fit:640/1*U8H1ne3vkauWzQzX5CdQUQ.jpeg",
            age: 9
        },
        {
            id: 7,
            isActive: true,
            fname: "Eve",
            lname: "Davis",
            username: "eved",
            password: "password123",
            gander: 'Male',
            budget: 0,
            email: "email 7",
            url: "https://wallpapercave.com/wp/wp5080768.jpg",
            age: 20
        },
        {
            id: 8,
            isActive: true,
            fname: "Frank",
            lname: "Miller",
            username: "frankm",
            password: "password123",
            gander: 'Male',
            budget: 0,
            email: "email 8",
            url: "https://images.pexels.com/photos/1071785/pexels-photo-1071785.jpeg?cs=srgb&dl=pexels-creationsbyfaik-1071785.jpg&fm=jpg",
            age: 39
        },
        {
            id: 9,
            isActive: true,
            fname: "Grace",
            lname: "Lee",
            username: "gracel",
            password: "password123",
            gander: 'Male',
            budget: 0,
            email: "email 9",
            url: "https://play-lh.googleusercontent.com/tryRowcXJHdoAT0SIO-WBxEdudjvZmTicjuVHJuadKAJ76KgKiq22hMqDXB9sCq3pw=w240-h480-rw",
            age: 22
        },
        {
            id: 10,
            isActive: true,
            fname: "Henry",
            lname: "Clark",
            username: "henryc",
            password: "password123",
            gander: 'Male',
            budget: 0,
            email: "email 10",
            url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ6BAHlIuDPK6lkExHi1DWN6cdzB2OJkmSSMNxEhQXpLnHQ3fslHw7AqUJsZEDvu85xhWw&usqp=CAU",
            age: 20
        }
    ],
}

export default DATA